# Generated by Django 4.1.2 on 2022-10-20 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_alter_product_sale_price'),
        ('customers', '0004_alter_customer_ruc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Total del Detalle')),
                ('total_without_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Total del Detalle sin Descuento')),
                ('product_id', models.ForeignKey(blank=True, db_column='product', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de orden',
                'db_table': 'detail_order',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9, unique=True, verbose_name='Código')),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Sub Total')),
                ('sub_total_without_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Total a pagar Sin Descuento')),
                ('igv', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Igv')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Total a pagar')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Monto Descuento')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('delivery_at', models.DateTimeField(verbose_name='Fecha de Entrega')),
                ('customer_id', models.ForeignKey(blank=True, db_column='customer', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Cliente')),
                ('detail_id', models.ManyToManyField(to='orders.detailorder')),
            ],
            options={
                'verbose_name': 'Orden',
                'db_table': 'order',
            },
        ),
    ]
