# Generated by Django 4.1.2 on 2022-10-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailorder',
            options={'verbose_name': 'Detalle de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido'},
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
    ]
