# Generated by Django 4.1.2 on 2022-10-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailorder',
            name='total_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Sub Total'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Sub Total'),
        ),
    ]
