# Generated by Django 4.1.2 on 2022-10-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código de Cliente')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Moficación')),
            ],
            options={
                'verbose_name': 'Categoría de Cliente',
                'db_table': 'customer_category',
            },
        ),
    ]
