# Generated by Django 4.1.2 on 2022-10-16 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.PositiveIntegerField(unique=True, verbose_name='Ruc')),
                ('name', models.CharField(default=None, max_length=60, verbose_name='Razon Social')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Moficación')),
                ('category_id', models.ForeignKey(db_column='category_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.customercategory', verbose_name='Categoría del Cliente')),
                ('district_id', models.ForeignKey(db_column='district_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.district', verbose_name='Distrito')),
            ],
            options={
                'verbose_name': 'Cliente',
                'db_table': 'customer',
            },
        ),
    ]
