# Generated by Django 4.1.2 on 2022-10-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ruc',
            field=models.CharField(max_length=11, unique=True, verbose_name='Ruc'),
        ),
    ]
