# Generated by Django 4.1.2 on 2022-10-15 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMeasure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Moficación')),
                ('unit_measure_category_id', models.ForeignKey(db_column='unit_measure_category_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='products.unitmeasurecategory', verbose_name='Categoría de Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Unidades de Medida',
                'db_table': 'unit_measure',
            },
        ),
    ]
