# Generated by Django 4.1.2 on 2022-10-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
